# -*- coding: utf-8 -*-
"""mainExperiment.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1egkI_HaxkrV7hqCqGr-7kT9pTc7_cN7o

# Register Shift in Grounded QA

## What this notebook does
1. Loads the cleaned dataset with **neutral / formal / informal** question variants.
2. Converts the data into **long format** so each row is one `(example, register)` prompt.
3. Loads a single instruction-tuned model.
4. Runs grounded QA with a fixed prompt.
5. Scores outputs with **exact match**, **lenient match**, and **abstention**.
6. Produces paper-ready tables for:
   - overall results by register
   - results by context variant
   - paired register-difference summaries
   - qualitative error-analysis candidates

## Before you run this notebook
- Use a **GPU runtime** in Colab if possible.
- Upload `confiqa_register_eval_cleaned.csv` to the Colab session.
- The notebook assumes the cleaned CSV filename is exactly:

```python
confiqa_register_eval_cleaned.csv
```

## 1. Install dependencies
"""

!pip install -q "transformers==4.41.2" datasets pandas tqdm accelerate sentencepiece matplotlib

"""## 2. Imports and basic settings"""

import ast
import re
import pandas as pd
import torch
import matplotlib.pyplot as plt

from tqdm import tqdm
from transformers import AutoTokenizer, AutoModelForSeq2SeqLM

# Experiment settings
CLEAN_DATASET_PATH = "confiqa_register_eval_cleaned.csv"
MODEL_NAME = "google/flan-t5-base"
MAX_NEW_TOKENS = 40
USE_GPU = torch.cuda.is_available()

print("GPU available:", USE_GPU)

"""## 3. Load the cleaned dataset

The cleaned dataset should already contain:
- `question_neutral`
- `question_formal`
- `question_informal`

The rest of the notebook builds the actual experiment from this file.
"""

df = pd.read_csv(CLEAN_DATASET_PATH)

print("Cleaned dataset shape:", df.shape)
display(df.head())

"""## 4. Convert the dataset to long format

Each original row contains three register versions of the same question.
This cell expands each row into **three experiment rows**:
- neutral
- formal
- informal

"""

records = []

for _, row in df.iterrows():
    for register in ["neutral", "formal", "informal"]:
        aliases = row["gold_aliases"]
        try:
            aliases = ast.literal_eval(aliases) if isinstance(aliases, str) else []
            if not isinstance(aliases, list):
                aliases = []
        except:
            aliases = []

        records.append({
            "example_id": row["example_id"],
            "source_dataset": row["source_dataset"],
            "subset": row["subset"],
            "split": row["split"],
            "source_row_idx": row["source_row_idx"],
            "context_variant": row["context_variant"],
            "register": register,
            "question": row[f"question_{register}"],
            "context": row["context"],
            "gold_answer": row["gold_answer"],
            "gold_aliases": aliases,
        })

exp_df = pd.DataFrame(records)
exp_df.to_csv("confiqa_register_eval_long.csv", index=False)

print("Long-format experiment shape:", exp_df.shape)
display(exp_df.head())

"""## 5. Load the model

This notebook uses a single instruction-tuned model for the main experiment.
"""

tokenizer = AutoTokenizer.from_pretrained(MODEL_NAME)
model = AutoModelForSeq2SeqLM.from_pretrained(MODEL_NAME)

device = "cuda" if torch.cuda.is_available() else "cpu"
model = model.to(device)

print("Running on:", device)

"""## 6. Define the prompt and generation function

The model is instructed to answer **using only the passage** and to abstain with
`insufficient evidence` when the context does not support a confident answer.
"""

def build_prompt(context, question):
    return f"""Answer the question using only the provided passage.
If the passage does not contain enough information, answer exactly: insufficient evidence.

Passage:
{context}

Question:
{question}

Answer:"""

def generate_answer(context, question, max_new_tokens=MAX_NEW_TOKENS):
    prompt = build_prompt(context, question)
    inputs = tokenizer(
        prompt,
        return_tensors="pt",
        truncation=True,
        max_length=1024
    ).to(device)

    with torch.no_grad():
        outputs = model.generate(
            **inputs,
            max_new_tokens=max_new_tokens,
            do_sample=False
        )

    text = tokenizer.decode(outputs[0], skip_special_tokens=True).strip()
    return text

"""## 7. Define scoring functions

This section creates:
- **exact correctness**
- **lenient correctness**
- **abstention detection**

The lenient metric helps with near-matches such as minor phrasing differences.
"""

def normalize_text(s):
    s = str(s).lower().strip()
    s = re.sub(r"\s+", " ", s)
    s = re.sub(r"[^\w\s]", "", s)
    return s

def parse_aliases(x):
    if isinstance(x, list):
        return x
    if pd.isna(x):
        return []
    try:
        val = ast.literal_eval(x)
        return val if isinstance(val, list) else []
    except:
        return []

def is_correct(pred, gold, aliases):
    pred_n = normalize_text(pred)
    gold_n = normalize_text(gold)

    if pred_n == gold_n:
        return 1

    for a in aliases:
        if pred_n == normalize_text(a):
            return 1

    return 0

def is_correct_lenient(pred, gold, aliases):
    pred_n = normalize_text(pred)
    gold_n = normalize_text(gold)

    if pred_n == gold_n or pred_n in gold_n or gold_n in pred_n:
        return 1

    for a in aliases:
        a_n = normalize_text(a)
        if pred_n == a_n or pred_n in a_n or a_n in pred_n:
            return 1

    return 0

def is_abstain(pred):
    return normalize_text(pred) == "insufficient evidence"

"""## 8. Run the full experiment

This cell runs the model on **all rows** in the long-format dataset and stores the predictions.
"""

full_df = exp_df.copy()

predictions = []
for _, row in tqdm(full_df.iterrows(), total=len(full_df), desc="Running full dataset"):
    pred = generate_answer(row["context"], row["question"])
    predictions.append(pred)

full_df["prediction"] = predictions

full_df["gold_aliases"] = full_df["gold_aliases"].apply(parse_aliases)
full_df["correct"] = full_df.apply(
    lambda r: is_correct(r["prediction"], r["gold_answer"], r["gold_aliases"]),
    axis=1
)
full_df["correct_lenient"] = full_df.apply(
    lambda r: is_correct_lenient(r["prediction"], r["gold_answer"], r["gold_aliases"]),
    axis=1
)
full_df["abstained"] = full_df["prediction"].apply(is_abstain)

full_df.to_csv("full_register_results.csv", index=False)

print("Saved full_register_results.csv")
display(full_df.head())

"""### 9. Main results table

This is the primary table:
- one row per register
- exact accuracy
- lenient accuracy
- abstention rate
"""

main_table = full_df.groupby("register").agg(
    n=("example_id", "count"),
    accuracy_exact=("correct", "mean"),
    accuracy_lenient=("correct_lenient", "mean"),
    abstention_rate=("abstained", "mean"),
).reset_index()

for col in ["accuracy_exact", "accuracy_lenient", "abstention_rate"]:
    main_table[col] = (100 * main_table[col]).round(1)

main_table = main_table.sort_values("register")

main_table_display = main_table.rename(columns={
    "register": "Register",
    "n": "N",
    "accuracy_exact": "Exact Acc. (%)",
    "accuracy_lenient": "Lenient Acc. (%)",
    "abstention_rate": "Abstention (%)"
})

display(main_table_display)
main_table.to_csv("table_main_results.csv", index=False)

"""## 10. Results by context variant

This table splits results by:
- `original` context
- `modified` context

"""

variant_table = full_df.groupby(["context_variant", "register"]).agg(
    n=("example_id", "count"),
    accuracy_exact=("correct", "mean"),
    accuracy_lenient=("correct_lenient", "mean"),
    abstention_rate=("abstained", "mean"),
).reset_index()

for col in ["accuracy_exact", "accuracy_lenient", "abstention_rate"]:
    variant_table[col] = (100 * variant_table[col]).round(1)

variant_table = variant_table.sort_values(["context_variant", "register"])

display(variant_table)
variant_table.to_csv("table_variant_results.csv", index=False)

"""## 11. Paired register-difference summary

Each `(example_id, context_variant)` group appears in three registers.
This cell counts how often correctness or abstention changes across those paired register versions.
"""

paired = full_df[[
    "example_id", "context_variant", "register",
    "question", "context", "gold_answer", "prediction",
    "correct", "correct_lenient", "abstained"
]].sort_values(["example_id", "context_variant", "register"])

group_summary = paired.groupby(["example_id", "context_variant"]).agg(
    exact_varies=("correct", lambda x: x.nunique() > 1),
    lenient_varies=("correct_lenient", lambda x: x.nunique() > 1),
    abstention_varies=("abstained", lambda x: x.nunique() > 1),
).reset_index()

paired_diff_summary = pd.DataFrame({
    "metric": ["exact correctness", "lenient correctness", "abstention"],
    "num_groups_with_difference": [
        int(group_summary["exact_varies"].sum()),
        int(group_summary["lenient_varies"].sum()),
        int(group_summary["abstention_varies"].sum()),
    ],
    "num_total_groups": [len(group_summary)] * 3
})

paired_diff_summary["percent_groups_with_difference"] = (
    100 * paired_diff_summary["num_groups_with_difference"] / paired_diff_summary["num_total_groups"]
).round(1)

display(paired_diff_summary)
paired_diff_summary.to_csv("table_paired_diff_summary.csv", index=False)

"""## 12. Collect register-sensitive examples for qualitative analysis

Useful examples for:
- groups where correctness changes across registers
- groups where abstention changes across registers
"""

interesting_groups = group_summary[
    group_summary["lenient_varies"] | group_summary["abstention_varies"]
][["example_id", "context_variant"]]

interesting_examples = paired.merge(
    interesting_groups,
    on=["example_id", "context_variant"]
).sort_values(["example_id", "context_variant", "register"])

display(
    interesting_examples[[
        "example_id", "context_variant", "register",
        "question", "gold_answer", "prediction",
        "correct", "correct_lenient", "abstained"
    ]].head(30)
)

interesting_examples.to_csv("error_analysis_candidates.csv", index=False)
print("Saved error_analysis_candidates.csv")

"""## 13. Collect stable failures

These examples failed in all three registers.
"""

stable_failure_groups = paired.groupby(["example_id", "context_variant"]).filter(
    lambda g: (g["correct_lenient"] == 0).all()
)

display(
    stable_failure_groups[[
        "example_id", "context_variant", "register",
        "question", "gold_answer", "prediction",
        "correct_lenient"
    ]].head(30)
)

stable_failure_groups.to_csv("stable_failures.csv", index=False)
print("Saved stable_failures.csv")

"""## 14. Quick plots

"""

plot_df = main_table.copy()

plt.figure(figsize=(6, 4))
plt.bar(plot_df["register"], plot_df["accuracy_exact"])
plt.ylabel("Exact Accuracy (%)")
plt.xlabel("Register")
plt.title("Exact Accuracy by Register")
plt.ylim(0, 100)
plt.show()

plt.figure(figsize=(6, 4))
plt.bar(plot_df["register"], plot_df["accuracy_lenient"])
plt.ylabel("Lenient Accuracy (%)")
plt.xlabel("Register")
plt.title("Lenient Accuracy by Register")
plt.ylim(0, 100)
plt.show()

"""## 15. Final checklist

### Saved files
- `confiqa_register_eval_long.csv`
- `full_register_results.csv`
- `table_main_results.csv`
- `table_variant_results.csv`
- `table_paired_diff_summary.csv`
- `error_analysis_candidates.csv`
- `stable_failures.csv`

### Key outputs for the paper
- overall results by register
- original vs modified context breakdown
- paired register-difference summary
- qualitative examples for error analysis

"""